const dummy_tags = {
    "_AdvancedTags": "true",
    "_AdvancedTags.a4GATE_B_SiteManager": "true",
    "_AdvancedTags.a4GATE_B_tfhttpxferb": "true",
    "_AdvancedTags.a4GATE_SiteManager_Color": "true",
    "_AdvancedTags.a4GATE_SiteManager_Status": "true",
    "_AdvancedTags.a4GATE_U2U_BIDIR": "true",
    "_AdvancedTags.a4GATE_U2U_RT": "true",
    "_ConnectionSharing": "true",
    "_CustomAlarms": "true",
    "_DataLogger": "true",
    "_EFMExporter": "true",
    "_IDF_for_Splunk": "true",
    "_IoT_Gateway": "true",
    "_IoT_Gateway.EMS_template": "true",
    "_IoT_Gateway.HTTP_Data Type Examples_16 Bit Device": "true",
    "_IoT_Gateway.Internal": "true",
    "_IoT_Gateway.TWA_template": "true",
    "_LocalHistorian": "true",
    "_Redundancy": "true",
    "_Scheduler": "true",
    "_SecurityPolicies": "true",
    "_SNMP Agent": "true",
    "_System": "true",
    "_ThingWorx": "true",
    "a4GATE": "true",
    "a4GATE.A": "true",
    "a4GATE.A._Hints.D0.0-D9999.0...D0.7-D9999.7 Boolean": "true",
    "a4GATE.A._Hints.D0-D9992 [r][c] Double Array": "true",
    "a4GATE.A._Hints.D0-D9992 Double": "true",
    "a4GATE.A._Hints.D0-D9996 [r][c] DWord Array": "true",
    "a4GATE.A._Hints.D0-D9996 [r][c] Float Array": "true",
    "a4GATE.A._Hints.D0-D9996 [r][c] LBCD Array": "true",
    "a4GATE.A._Hints.D0-D9996 [r][c] Long Array": "true",
    "a4GATE.A._Hints.D0-D9996 DWord": "true",
    "a4GATE.A._Hints.D0-D9996 Float": "true",
    "a4GATE.A._Hints.D0-D9996 LBCD": "true",
    "a4GATE.A._Hints.D0-D9996 Long": "true",
    "a4GATE.A._Hints.D0-D9998 [r][c] BCD Array": "true",
    "a4GATE.A._Hints.D0-D9998 [r][c] Short Array": "true",
    "a4GATE.A._Hints.D0-D9998 [r][c] Word Array": "true",
    "a4GATE.A._Hints.D0-D9998 BCD": "true",
    "a4GATE.A._Hints.D0-D9998 Short": "true",
    "a4GATE.A._Hints.D0-D9998 Word": "true",
    "a4GATE.A._Hints.D0-D9999 [r][c] Byte Array": "true",
    "a4GATE.A._Hints.D0-D9999 [r][c] Char Array": "true",
    "a4GATE.A._Hints.D0-D9999 Byte": "true",
    "a4GATE.A._Hints.D0-D9999 Char": "true",
    "a4GATE.A._Hints.S0-S999 String": "true",
    "a4GATE.A.CPU": "true",
    "a4GATE.A.Disk": "true",
    "a4GATE.A.FT": "true",
    "a4GATE.A.RAM": "true",
    "a4GATE.A.Uptime": "true",
    "a4GATE.B": "true",
    "a4GATE.B._Hints.D0.0-D9999.0...D0.7-D9999.7 Boolean": "true",
    "a4GATE.B._Hints.D0-D9992 [r][c] Double Array": "true",
    "a4GATE.B._Hints.D0-D9992 Double": "true",
    "a4GATE.B._Hints.D0-D9996 [r][c] DWord Array": "true",
    "a4GATE.B._Hints.D0-D9996 [r][c] Float Array": "true",
    "a4GATE.B._Hints.D0-D9996 [r][c] LBCD Array": "true",
    "a4GATE.B._Hints.D0-D9996 [r][c] Long Array": "true",
    "a4GATE.B._Hints.D0-D9996 DWord": "true",
    "a4GATE.B._Hints.D0-D9996 Float": "true",
    "a4GATE.B._Hints.D0-D9996 LBCD": "true",
    "a4GATE.B._Hints.D0-D9996 Long": "true",
    "a4GATE.B._Hints.D0-D9998 [r][c] BCD Array": "true",
    "a4GATE.B._Hints.D0-D9998 [r][c] Short Array": "true",
    "a4GATE.B._Hints.D0-D9998 [r][c] Word Array": "true",
    "a4GATE.B._Hints.D0-D9998 BCD": "true",
    "a4GATE.B._Hints.D0-D9998 Short": "true",
    "a4GATE.B._Hints.D0-D9998 Word": "true",
    "a4GATE.B._Hints.D0-D9999 [r][c] Byte Array": "true",
    "a4GATE.B._Hints.D0-D9999 [r][c] Char Array": "true",
    "a4GATE.B._Hints.D0-D9999 Byte": "true",
    "a4GATE.B._Hints.D0-D9999 Char": "true",
    "a4GATE.B._Hints.S0-S999 String": "true",
    "a4GATE.B.SiteManager": "true",
    "a4GATE.B.tf_http_xfer_b": "true",
    "a4GATE.SiteManager": "true",
    "a4GATE.SiteManager._Hints.D0.0-D9999.0...D0.7-D9999.7 Boolean": "true",
    "a4GATE.SiteManager._Hints.D0-D9992 [r][c] Double Array": "true",
    "a4GATE.SiteManager._Hints.D0-D9992 Double": "true",
    "a4GATE.SiteManager._Hints.D0-D9996 [r][c] DWord Array": "true",
    "a4GATE.SiteManager._Hints.D0-D9996 [r][c] Float Array": "true",
    "a4GATE.SiteManager._Hints.D0-D9996 [r][c] LBCD Array": "true",
    "a4GATE.SiteManager._Hints.D0-D9996 [r][c] Long Array": "true",
    "a4GATE.SiteManager._Hints.D0-D9996 DWord": "true",
    "a4GATE.SiteManager._Hints.D0-D9996 Float": "true",
    "a4GATE.SiteManager._Hints.D0-D9996 LBCD": "true",
    "a4GATE.SiteManager._Hints.D0-D9996 Long": "true",
    "a4GATE.SiteManager._Hints.D0-D9998 [r][c] BCD Array": "true",
    "a4GATE.SiteManager._Hints.D0-D9998 [r][c] Short Array": "true",
    "a4GATE.SiteManager._Hints.D0-D9998 [r][c] Word Array": "true",
    "a4GATE.SiteManager._Hints.D0-D9998 BCD": "true",
    "a4GATE.SiteManager._Hints.D0-D9998 Short": "true",
    "a4GATE.SiteManager._Hints.D0-D9998 Word": "true",
    "a4GATE.SiteManager._Hints.D0-D9999 [r][c] Byte Array": "true",
    "a4GATE.SiteManager._Hints.D0-D9999 [r][c] Char Array": "true",
    "a4GATE.SiteManager._Hints.D0-D9999 Byte": "true",
    "a4GATE.SiteManager._Hints.D0-D9999 Char": "true",
    "a4GATE.SiteManager._Hints.S0-S999 String": "true",
    "a4GATE.SiteManager.Color": "true",
    "a4GATE.SiteManager.Status": "true",
    "a4GATE.U2U": "true",
    "a4GATE.U2U._Hints.D0.0-D9999.0...D0.7-D9999.7 Boolean": "true",
    "a4GATE.U2U._Hints.D0-D9992 [r][c] Double Array": "true",
    "a4GATE.U2U._Hints.D0-D9992 Double": "true",
    "a4GATE.U2U._Hints.D0-D9996 [r][c] DWord Array": "true",
    "a4GATE.U2U._Hints.D0-D9996 [r][c] Float Array": "true",
    "a4GATE.U2U._Hints.D0-D9996 [r][c] LBCD Array": "true",
    "a4GATE.U2U._Hints.D0-D9996 [r][c] Long Array": "true",
    "a4GATE.U2U._Hints.D0-D9996 DWord": "true",
    "a4GATE.U2U._Hints.D0-D9996 Float": "true",
    "a4GATE.U2U._Hints.D0-D9996 LBCD": "true",
    "a4GATE.U2U._Hints.D0-D9996 Long": "true",
    "a4GATE.U2U._Hints.D0-D9998 [r][c] BCD Array": "true",
    "a4GATE.U2U._Hints.D0-D9998 [r][c] Short Array": "true",
    "a4GATE.U2U._Hints.D0-D9998 [r][c] Word Array": "true",
    "a4GATE.U2U._Hints.D0-D9998 BCD": "true",
    "a4GATE.U2U._Hints.D0-D9998 Short": "true",
    "a4GATE.U2U._Hints.D0-D9998 Word": "true",
    "a4GATE.U2U._Hints.D0-D9999 [r][c] Byte Array": "true",
    "a4GATE.U2U._Hints.D0-D9999 [r][c] Char Array": "true",
    "a4GATE.U2U._Hints.D0-D9999 Byte": "true",
    "a4GATE.U2U._Hints.D0-D9999 Char": "true",
    "a4GATE.U2U._Hints.S0-S999 String": "true",
    "a4GATE.U2U.BIDIR": "true",
    "a4GATE.U2U.RT": "true",
    "Data Type Examples": "true",
    "Data Type Examples.16 Bit Device": "true",
    "Data Type Examples.16 Bit Device._Hints.B0-B9999 [r][c] Boolean Array": "true",
    "Data Type Examples.16 Bit Device._Hints.B0-B9999 Boolean": "true",
    "Data Type Examples.16 Bit Device._Hints.K0.0-K9999.0...K0.15-K9999.15 Boolean": "true",
    "Data Type Examples.16 Bit Device._Hints.K0-K9996 [r][c] Date Array": "true",
    "Data Type Examples.16 Bit Device._Hints.K0-K9996 [r][c] Double Array": "true",
    "Data Type Examples.16 Bit Device._Hints.K0-K9996 [r][c] LLong Array": "true",
    "Data Type Examples.16 Bit Device._Hints.K0-K9996 [r][c] QWord Array": "true",
    "Data Type Examples.16 Bit Device._Hints.K0-K9996 Date": "true",
    "Data Type Examples.16 Bit Device._Hints.K0-K9996 Double": "true",
    "Data Type Examples.16 Bit Device._Hints.K0-K9996 LLong": "true",
    "Data Type Examples.16 Bit Device._Hints.K0-K9996 QWord": "true",
    "Data Type Examples.16 Bit Device._Hints.K0-K9998 [r][c] DWord Array": "true",
    "Data Type Examples.16 Bit Device._Hints.K0-K9998 [r][c] Float Array": "true",
    "Data Type Examples.16 Bit Device._Hints.K0-K9998 [r][c] LBCD Array": "true",
    "Data Type Examples.16 Bit Device._Hints.K0-K9998 [r][c] Long Array": "true",
    "Data Type Examples.16 Bit Device._Hints.K0-K9998 DWord": "true",
    "Data Type Examples.16 Bit Device._Hints.K0-K9998 Float": "true",
    "Data Type Examples.16 Bit Device._Hints.K0-K9998 LBCD": "true",
    "Data Type Examples.16 Bit Device._Hints.K0-K9998 Long": "true",
    "Data Type Examples.16 Bit Device._Hints.K0-K9999 [r][c] BCD Array": "true",
    "Data Type Examples.16 Bit Device._Hints.K0-K9999 [r][c] Boolean Array": "true",
    "Data Type Examples.16 Bit Device._Hints.K0-K9999 [r][c] Short Array": "true",
    "Data Type Examples.16 Bit Device._Hints.K0-K9999 [r][c] Word Array": "true",
    "Data Type Examples.16 Bit Device._Hints.K0-K9999 BCD": "true",
    "Data Type Examples.16 Bit Device._Hints.K0-K9999 Boolean": "true",
    "Data Type Examples.16 Bit Device._Hints.K0-K9999 Short": "true",
    "Data Type Examples.16 Bit Device._Hints.K0-K9999 Word": "true",
    "Data Type Examples.16 Bit Device._Hints.R0.0-R9999.0...R0.15-R9999.15 Boolean": "true",
    "Data Type Examples.16 Bit Device._Hints.R0-R9996 [r][c] Date Array": "true",
    "Data Type Examples.16 Bit Device._Hints.R0-R9996 [r][c] Double Array": "true",
    "Data Type Examples.16 Bit Device._Hints.R0-R9996 [r][c] LLong Array": "true",
    "Data Type Examples.16 Bit Device._Hints.R0-R9996 [r][c] QWord Array": "true",
    "Data Type Examples.16 Bit Device._Hints.R0-R9996 Date": "true",
    "Data Type Examples.16 Bit Device._Hints.R0-R9996 Double": "true",
    "Data Type Examples.16 Bit Device._Hints.R0-R9996 LLong": "true",
    "Data Type Examples.16 Bit Device._Hints.R0-R9996 QWord": "true",
    "Data Type Examples.16 Bit Device._Hints.R0-R9998 [r][c] DWord Array": "true",
    "Data Type Examples.16 Bit Device._Hints.R0-R9998 [r][c] Float Array": "true",
    "Data Type Examples.16 Bit Device._Hints.R0-R9998 [r][c] LBCD Array": "true",
    "Data Type Examples.16 Bit Device._Hints.R0-R9998 [r][c] Long Array": "true",
    "Data Type Examples.16 Bit Device._Hints.R0-R9998 DWord": "true",
    "Data Type Examples.16 Bit Device._Hints.R0-R9998 Float": "true",
    "Data Type Examples.16 Bit Device._Hints.R0-R9998 LBCD": "true",
    "Data Type Examples.16 Bit Device._Hints.R0-R9998 Long": "true",
    "Data Type Examples.16 Bit Device._Hints.R0-R9999 [r][c] BCD Array": "true",
    "Data Type Examples.16 Bit Device._Hints.R0-R9999 [r][c] Boolean Array": "true",
    "Data Type Examples.16 Bit Device._Hints.R0-R9999 [r][c] Short Array": "true",
    "Data Type Examples.16 Bit Device._Hints.R0-R9999 [r][c] Word Array": "true",
    "Data Type Examples.16 Bit Device._Hints.R0-R9999 BCD": "true",
    "Data Type Examples.16 Bit Device._Hints.R0-R9999 Boolean": "true",
    "Data Type Examples.16 Bit Device._Hints.R0-R9999 Short": "true",
    "Data Type Examples.16 Bit Device._Hints.R0-R9999 Word": "true",
    "Data Type Examples.16 Bit Device._Hints.RAMP (Rate, Low Limit [0.0 - 4294967295.0], High Limit [0.0 - 4294967295.0], Increment) DWord": "true",
    "Data Type Examples.16 Bit Device._Hints.RAMP (Rate, Low Limit [0.0 - 65535.0], High Limit [0.0 - 65535.0], Increment) Word": "true",
    "Data Type Examples.16 Bit Device._Hints.RAMP (Rate, Low Limit [-2147483648.0 - 2147483647.0], High Limit [-2147483648.0 - 2147483647.0], Increment) Long": "true",
    "Data Type Examples.16 Bit Device._Hints.RAMP (Rate, Low Limit [-32768.0 - 32767.0], High Limit [-32768.0 - 32767.0], Increment) Short": "true",
    "Data Type Examples.16 Bit Device._Hints.RAMP (Rate, Low Limit, High Limit, Increment) Double": "true",
    "Data Type Examples.16 Bit Device._Hints.RAMP (Rate, Low Limit, High Limit, Increment) Float": "true",
    "Data Type Examples.16 Bit Device._Hints.RAMP (Rate, Low Limit, High Limit, Increment) LLong": "true",
    "Data Type Examples.16 Bit Device._Hints.RAMP (Rate, Low Limit, High Limit, Increment) QWord": "true",
    "Data Type Examples.16 Bit Device._Hints.RANDOM (Rate, Low Limit [0.0 - 4294967295.0], High Limit [0.0 - 4294967295.0]) DWord": "true",
    "Data Type Examples.16 Bit Device._Hints.RANDOM (Rate, Low Limit [0.0 - 65535.0], High Limit [0.0 - 65535.0]) Word": "true",
    "Data Type Examples.16 Bit Device._Hints.RANDOM (Rate, Low Limit [-2147483648.0 - 2147483647.0], High Limit [-2147483648.0 - 2147483647.0]) Long": "true",
    "Data Type Examples.16 Bit Device._Hints.RANDOM (Rate, Low Limit [-32768.0 - 32767.0], High Limit [-32768.0 - 32767.0]) Short": "true",
    "Data Type Examples.16 Bit Device._Hints.RANDOM (Rate, Low Limit, High Limit) Double": "true",
    "Data Type Examples.16 Bit Device._Hints.RANDOM (Rate, Low Limit, High Limit) Float": "true",
    "Data Type Examples.16 Bit Device._Hints.RANDOM (Rate, Low Limit, High Limit) LLong": "true",
    "Data Type Examples.16 Bit Device._Hints.RANDOM (Rate, Low Limit, High Limit) QWord": "true",
    "Data Type Examples.16 Bit Device._Hints.S0-S999 [r][c] String Array": "true",
    "Data Type Examples.16 Bit Device._Hints.S0-S999 String": "true",
    "Data Type Examples.16 Bit Device._Hints.SINE (Rate [10-1000], Low Limit, High Limit, Frequency [0.01-5.0], Phase) Double": "true",
    "Data Type Examples.16 Bit Device._Hints.SINE (Rate [10-1000], Low Limit, High Limit, Frequency [0.01-5.0], Phase) Float": "true",
    "Data Type Examples.16 Bit Device._Hints.USER (Rate, UserVal1, UserVal2, ... , UserValN) Boolean": "true",
    "Data Type Examples.16 Bit Device._Hints.USER (Rate, UserVal1, UserVal2, ... , UserValN) Double": "true",
    "Data Type Examples.16 Bit Device._Hints.USER (Rate, UserVal1, UserVal2, ... , UserValN) DWord": "true",
    "Data Type Examples.16 Bit Device._Hints.USER (Rate, UserVal1, UserVal2, ... , UserValN) Float": "true",
    "Data Type Examples.16 Bit Device._Hints.USER (Rate, UserVal1, UserVal2, ... , UserValN) LLong": "true",
    "Data Type Examples.16 Bit Device._Hints.USER (Rate, UserVal1, UserVal2, ... , UserValN) Long": "true",
    "Data Type Examples.16 Bit Device._Hints.USER (Rate, UserVal1, UserVal2, ... , UserValN) QWord": "true",
    "Data Type Examples.16 Bit Device._Hints.USER (Rate, UserVal1, UserVal2, ... , UserValN) Short": "true",
    "Data Type Examples.16 Bit Device._Hints.USER (Rate, UserVal1, UserVal2, ... , UserValN) String": "true",
    "Data Type Examples.16 Bit Device._Hints.USER (Rate, UserVal1, UserVal2, ... , UserValN) Word": "true",
    "Data Type Examples.16 Bit Device.B Registers": "true",
    "Data Type Examples.16 Bit Device.B Registers.Boolean1": "true",
    "Data Type Examples.16 Bit Device.B Registers.Boolean2": "true",
    "Data Type Examples.16 Bit Device.B Registers.Boolean3": "true",
    "Data Type Examples.16 Bit Device.B Registers.Boolean4": "true",
    "Data Type Examples.16 Bit Device.B Registers.BooleanArray": "true",
    "Data Type Examples.16 Bit Device.K Registers": "true",
    "Data Type Examples.16 Bit Device.K Registers.Boolean1": "true",
    "Data Type Examples.16 Bit Device.K Registers.Boolean2": "true",
    "Data Type Examples.16 Bit Device.K Registers.Boolean3": "true",
    "Data Type Examples.16 Bit Device.K Registers.Boolean4": "true",
    "Data Type Examples.16 Bit Device.K Registers.Double1": "true",
    "Data Type Examples.16 Bit Device.K Registers.Double2": "true",
    "Data Type Examples.16 Bit Device.K Registers.Double3": "true",
    "Data Type Examples.16 Bit Device.K Registers.Double4": "true",
    "Data Type Examples.16 Bit Device.K Registers.DoubleArray": "true",
    "Data Type Examples.16 Bit Device.K Registers.DWord1": "true",
    "Data Type Examples.16 Bit Device.K Registers.DWord2": "true",
    "Data Type Examples.16 Bit Device.K Registers.DWord3": "true",
    "Data Type Examples.16 Bit Device.K Registers.DWord4": "true",
    "Data Type Examples.16 Bit Device.K Registers.DWordArray": "true",
    "Data Type Examples.16 Bit Device.K Registers.Float1": "true",
    "Data Type Examples.16 Bit Device.K Registers.Float2": "true",
    "Data Type Examples.16 Bit Device.K Registers.Float3": "true",
    "Data Type Examples.16 Bit Device.K Registers.Float4": "true",
    "Data Type Examples.16 Bit Device.K Registers.FloatArray": "true",
    "Data Type Examples.16 Bit Device.K Registers.LLong1": "true",
    "Data Type Examples.16 Bit Device.K Registers.LLong2": "true",
    "Data Type Examples.16 Bit Device.K Registers.LLong3": "true",
    "Data Type Examples.16 Bit Device.K Registers.LLong4": "true",
    "Data Type Examples.16 Bit Device.K Registers.LLongArray": "true",
    "Data Type Examples.16 Bit Device.K Registers.Long1": "true",
    "Data Type Examples.16 Bit Device.K Registers.Long2": "true",
    "Data Type Examples.16 Bit Device.K Registers.Long3": "true",
    "Data Type Examples.16 Bit Device.K Registers.Long4": "true",
    "Data Type Examples.16 Bit Device.K Registers.LongArray": "true",
    "Data Type Examples.16 Bit Device.K Registers.QWord1": "true",
    "Data Type Examples.16 Bit Device.K Registers.QWord2": "true",
    "Data Type Examples.16 Bit Device.K Registers.QWord3": "true",
    "Data Type Examples.16 Bit Device.K Registers.QWord4": "true",
    "Data Type Examples.16 Bit Device.K Registers.QWordArray": "true",
    "Data Type Examples.16 Bit Device.K Registers.Short1": "true",
    "Data Type Examples.16 Bit Device.K Registers.Short2": "true",
    "Data Type Examples.16 Bit Device.K Registers.Short3": "true",
    "Data Type Examples.16 Bit Device.K Registers.Short4": "true",
    "Data Type Examples.16 Bit Device.K Registers.ShortArray": "true",
    "Data Type Examples.16 Bit Device.K Registers.Word1": "true",
    "Data Type Examples.16 Bit Device.K Registers.Word2": "true",
    "Data Type Examples.16 Bit Device.K Registers.Word3": "true",
    "Data Type Examples.16 Bit Device.K Registers.Word4": "true",
    "Data Type Examples.16 Bit Device.K Registers.WordArray": "true",
    "Data Type Examples.16 Bit Device.R Registers": "true",
    "Data Type Examples.16 Bit Device.R Registers.Boolean1": "true",
    "Data Type Examples.16 Bit Device.R Registers.Boolean2": "true",
    "Data Type Examples.16 Bit Device.R Registers.Boolean3": "true",
    "Data Type Examples.16 Bit Device.R Registers.Boolean4": "true",
    "Data Type Examples.16 Bit Device.R Registers.Double1": "true",
    "Data Type Examples.16 Bit Device.R Registers.Double2": "true",
    "Data Type Examples.16 Bit Device.R Registers.Double3": "true",
    "Data Type Examples.16 Bit Device.R Registers.Double4": "true",
    "Data Type Examples.16 Bit Device.R Registers.DoubleArray": "true",
    "Data Type Examples.16 Bit Device.R Registers.DWord1": "true",
    "Data Type Examples.16 Bit Device.R Registers.DWord2": "true",
    "Data Type Examples.16 Bit Device.R Registers.DWord3": "true",
    "Data Type Examples.16 Bit Device.R Registers.DWord4": "true",
    "Data Type Examples.16 Bit Device.R Registers.DWordArray": "true",
    "Data Type Examples.16 Bit Device.R Registers.Float1": "true",
    "Data Type Examples.16 Bit Device.R Registers.Float2": "true",
    "Data Type Examples.16 Bit Device.R Registers.Float3": "true",
    "Data Type Examples.16 Bit Device.R Registers.Float4": "true",
    "Data Type Examples.16 Bit Device.R Registers.FloatArray": "true",
    "Data Type Examples.16 Bit Device.R Registers.LLong1": "true",
    "Data Type Examples.16 Bit Device.R Registers.LLong2": "true",
    "Data Type Examples.16 Bit Device.R Registers.LLong3": "true",
    "Data Type Examples.16 Bit Device.R Registers.LLong4": "true",
    "Data Type Examples.16 Bit Device.R Registers.LLongArray": "true",
    "Data Type Examples.16 Bit Device.R Registers.Long1": "true",
    "Data Type Examples.16 Bit Device.R Registers.Long2": "true",
    "Data Type Examples.16 Bit Device.R Registers.Long3": "true",
    "Data Type Examples.16 Bit Device.R Registers.Long4": "true",
    "Data Type Examples.16 Bit Device.R Registers.LongArray": "true",
    "Data Type Examples.16 Bit Device.R Registers.QWord1": "true",
    "Data Type Examples.16 Bit Device.R Registers.QWord2": "true",
    "Data Type Examples.16 Bit Device.R Registers.QWord3": "true",
    "Data Type Examples.16 Bit Device.R Registers.QWord4": "true",
    "Data Type Examples.16 Bit Device.R Registers.QWordArray": "true",
    "Data Type Examples.16 Bit Device.R Registers.Short1": "true",
    "Data Type Examples.16 Bit Device.R Registers.Short2": "true",
    "Data Type Examples.16 Bit Device.R Registers.Short3": "true",
    "Data Type Examples.16 Bit Device.R Registers.Short4": "true",
    "Data Type Examples.16 Bit Device.R Registers.ShortArray": "true",
    "Data Type Examples.16 Bit Device.R Registers.Word1": "true",
    "Data Type Examples.16 Bit Device.R Registers.Word2": "true",
    "Data Type Examples.16 Bit Device.R Registers.Word3": "true",
    "Data Type Examples.16 Bit Device.R Registers.Word4": "true",
    "Data Type Examples.16 Bit Device.R Registers.WordArray": "true",
    "Data Type Examples.16 Bit Device.S Registers": "true",
    "Data Type Examples.16 Bit Device.S Registers.String1": "true",
    "Data Type Examples.16 Bit Device.S Registers.String2": "true",
    "Data Type Examples.16 Bit Device.S Registers.String3": "true",
    "Data Type Examples.16 Bit Device.S Registers.String4": "true",
    "Data Type Examples.16 Bit Device.S Registers.StringArray[4]": "true",
    "Data Type Examples.8 Bit Device": "true",
    "Data Type Examples.8 Bit Device._Hints.B0-B9999 [r][c] Boolean Array": "true",
    "Data Type Examples.8 Bit Device._Hints.B0-B9999 Boolean": "true",
    "Data Type Examples.8 Bit Device._Hints.K0.0-K9999.0...K0.7-K9999.7 Boolean": "true",
    "Data Type Examples.8 Bit Device._Hints.K0-K9992 [r][c] Date Array": "true",
    "Data Type Examples.8 Bit Device._Hints.K0-K9992 [r][c] Double Array": "true",
    "Data Type Examples.8 Bit Device._Hints.K0-K9992 [r][c] LLong Array": "true",
    "Data Type Examples.8 Bit Device._Hints.K0-K9992 [r][c] QWord Array": "true",
    "Data Type Examples.8 Bit Device._Hints.K0-K9992 Date": "true",
    "Data Type Examples.8 Bit Device._Hints.K0-K9992 Double": "true",
    "Data Type Examples.8 Bit Device._Hints.K0-K9992 LLong": "true",
    "Data Type Examples.8 Bit Device._Hints.K0-K9992 QWord": "true",
    "Data Type Examples.8 Bit Device._Hints.K0-K9996 [r][c] DWord Array": "true",
    "Data Type Examples.8 Bit Device._Hints.K0-K9996 [r][c] Float Array": "true",
    "Data Type Examples.8 Bit Device._Hints.K0-K9996 [r][c] LBCD Array": "true",
    "Data Type Examples.8 Bit Device._Hints.K0-K9996 [r][c] Long Array": "true",
    "Data Type Examples.8 Bit Device._Hints.K0-K9996 DWord": "true",
    "Data Type Examples.8 Bit Device._Hints.K0-K9996 Float": "true",
    "Data Type Examples.8 Bit Device._Hints.K0-K9996 LBCD": "true",
    "Data Type Examples.8 Bit Device._Hints.K0-K9996 Long": "true",
    "Data Type Examples.8 Bit Device._Hints.K0-K9998 [r][c] BCD Array": "true",
    "Data Type Examples.8 Bit Device._Hints.K0-K9998 [r][c] Short Array": "true",
    "Data Type Examples.8 Bit Device._Hints.K0-K9998 [r][c] Word Array": "true",
    "Data Type Examples.8 Bit Device._Hints.K0-K9998 BCD": "true",
    "Data Type Examples.8 Bit Device._Hints.K0-K9998 Short": "true",
    "Data Type Examples.8 Bit Device._Hints.K0-K9998 Word": "true",
    "Data Type Examples.8 Bit Device._Hints.K0-K9999 [r][c] Boolean Array": "true",
    "Data Type Examples.8 Bit Device._Hints.K0-K9999 [r][c] Byte Array": "true",
    "Data Type Examples.8 Bit Device._Hints.K0-K9999 [r][c] Char Array": "true",
    "Data Type Examples.8 Bit Device._Hints.K0-K9999 Boolean": "true",
    "Data Type Examples.8 Bit Device._Hints.K0-K9999 Byte": "true",
    "Data Type Examples.8 Bit Device._Hints.K0-K9999 Char": "true",
    "Data Type Examples.8 Bit Device._Hints.R0.0-R9999.0...R0.7-R9999.7 Boolean": "true",
    "Data Type Examples.8 Bit Device._Hints.R0-R9992 [r][c] Date Array": "true",
    "Data Type Examples.8 Bit Device._Hints.R0-R9992 [r][c] Double Array": "true",
    "Data Type Examples.8 Bit Device._Hints.R0-R9992 [r][c] LLong Array": "true",
    "Data Type Examples.8 Bit Device._Hints.R0-R9992 [r][c] QWord Array": "true",
    "Data Type Examples.8 Bit Device._Hints.R0-R9992 Date": "true",
    "Data Type Examples.8 Bit Device._Hints.R0-R9992 Double": "true",
    "Data Type Examples.8 Bit Device._Hints.R0-R9992 LLong": "true",
    "Data Type Examples.8 Bit Device._Hints.R0-R9992 QWord": "true",
    "Data Type Examples.8 Bit Device._Hints.R0-R9996 [r][c] DWord Array": "true",
    "Data Type Examples.8 Bit Device._Hints.R0-R9996 [r][c] Float Array": "true",
    "Data Type Examples.8 Bit Device._Hints.R0-R9996 [r][c] LBCD Array": "true",
    "Data Type Examples.8 Bit Device._Hints.R0-R9996 [r][c] Long Array": "true",
    "Data Type Examples.8 Bit Device._Hints.R0-R9996 DWord": "true",
    "Data Type Examples.8 Bit Device._Hints.R0-R9996 Float": "true",
    "Data Type Examples.8 Bit Device._Hints.R0-R9996 LBCD": "true",
    "Data Type Examples.8 Bit Device._Hints.R0-R9996 Long": "true",
    "Data Type Examples.8 Bit Device._Hints.R0-R9998 [r][c] BCD Array": "true",
    "Data Type Examples.8 Bit Device._Hints.R0-R9998 [r][c] Short Array": "true",
    "Data Type Examples.8 Bit Device._Hints.R0-R9998 [r][c] Word Array": "true",
    "Data Type Examples.8 Bit Device._Hints.R0-R9998 BCD": "true",
    "Data Type Examples.8 Bit Device._Hints.R0-R9998 Short": "true",
    "Data Type Examples.8 Bit Device._Hints.R0-R9998 Word": "true",
    "Data Type Examples.8 Bit Device._Hints.R0-R9999 [r][c] Boolean Array": "true",
    "Data Type Examples.8 Bit Device._Hints.R0-R9999 [r][c] Byte Array": "true",
    "Data Type Examples.8 Bit Device._Hints.R0-R9999 [r][c] Char Array": "true",
    "Data Type Examples.8 Bit Device._Hints.R0-R9999 Boolean": "true",
    "Data Type Examples.8 Bit Device._Hints.R0-R9999 Byte": "true",
    "Data Type Examples.8 Bit Device._Hints.R0-R9999 Char": "true",
    "Data Type Examples.8 Bit Device._Hints.RAMP (Rate, Low Limit [0.0 - 255.0], High Limit [0.0 - 255.0], Increment) Byte": "true",
    "Data Type Examples.8 Bit Device._Hints.RAMP (Rate, Low Limit [0.0 - 4294967295.0], High Limit [0.0 - 4294967295.0], Increment) DWord": "true",
    "Data Type Examples.8 Bit Device._Hints.RAMP (Rate, Low Limit [0.0 - 65535.0], High Limit [0.0 - 65535.0], Increment) Word": "true",
    "Data Type Examples.8 Bit Device._Hints.RAMP (Rate, Low Limit [-128.0 - 127.0], High Limit [-128.0 - 127.0], Increment) Char": "true",
    "Data Type Examples.8 Bit Device._Hints.RAMP (Rate, Low Limit [-2147483648.0 - 2147483647.0], High Limit [-2147483648.0 - 2147483647.0], Increment) Long": "true",
    "Data Type Examples.8 Bit Device._Hints.RAMP (Rate, Low Limit [-32768.0 - 32767.0], High Limit [-32768.0 - 32767.0], Increment) Short": "true",
    "Data Type Examples.8 Bit Device._Hints.RAMP (Rate, Low Limit, High Limit, Increment) Double": "true",
    "Data Type Examples.8 Bit Device._Hints.RAMP (Rate, Low Limit, High Limit, Increment) Float": "true",
    "Data Type Examples.8 Bit Device._Hints.RAMP (Rate, Low Limit, High Limit, Increment) LLong": "true",
    "Data Type Examples.8 Bit Device._Hints.RAMP (Rate, Low Limit, High Limit, Increment) QWord": "true",
    "Data Type Examples.8 Bit Device._Hints.RANDOM (Rate, Low Limit [0.0 - 255.0], High Limit [0.0 - 255.0]) Byte": "true",
    "Data Type Examples.8 Bit Device._Hints.RANDOM (Rate, Low Limit [0.0 - 4294967295.0], High Limit [0.0 - 4294967295.0]) DWord": "true",
    "Data Type Examples.8 Bit Device._Hints.RANDOM (Rate, Low Limit [0.0 - 65535.0], High Limit [0.0 - 65535.0]) Word": "true",
    "Data Type Examples.8 Bit Device._Hints.RANDOM (Rate, Low Limit [-128.0 - 127.0], High Limit [-128.0 - 127.0]) Char": "true",
    "Data Type Examples.8 Bit Device._Hints.RANDOM (Rate, Low Limit [-2147483648.0 - 2147483647.0], High Limit [-2147483648.0 - 2147483647.0]) Long": "true",
    "Data Type Examples.8 Bit Device._Hints.RANDOM (Rate, Low Limit [-32768.0 - 32767.0], High Limit [-32768.0 - 32767.0]) Short": "true",
    "Data Type Examples.8 Bit Device._Hints.RANDOM (Rate, Low Limit, High Limit) Double": "true",
    "Data Type Examples.8 Bit Device._Hints.RANDOM (Rate, Low Limit, High Limit) Float": "true",
    "Data Type Examples.8 Bit Device._Hints.RANDOM (Rate, Low Limit, High Limit) LLong": "true",
    "Data Type Examples.8 Bit Device._Hints.RANDOM (Rate, Low Limit, High Limit) QWord": "true",
    "Data Type Examples.8 Bit Device._Hints.S0-S999 [r][c] String Array": "true",
    "Data Type Examples.8 Bit Device._Hints.S0-S999 String": "true",
    "Data Type Examples.8 Bit Device._Hints.SINE (Rate [10-1000], Low Limit, High Limit, Frequency [0.01-5.0], Phase) Double": "true",
    "Data Type Examples.8 Bit Device._Hints.SINE (Rate [10-1000], Low Limit, High Limit, Frequency [0.01-5.0], Phase) Float": "true",
    "Data Type Examples.8 Bit Device._Hints.USER (Rate, UserVal1, UserVal2, ... , UserValN) Boolean": "true",
    "Data Type Examples.8 Bit Device._Hints.USER (Rate, UserVal1, UserVal2, ... , UserValN) Byte": "true",
    "Data Type Examples.8 Bit Device._Hints.USER (Rate, UserVal1, UserVal2, ... , UserValN) Char": "true",
    "Data Type Examples.8 Bit Device._Hints.USER (Rate, UserVal1, UserVal2, ... , UserValN) Double": "true",
    "Data Type Examples.8 Bit Device._Hints.USER (Rate, UserVal1, UserVal2, ... , UserValN) DWord": "true",
    "Data Type Examples.8 Bit Device._Hints.USER (Rate, UserVal1, UserVal2, ... , UserValN) Float": "true",
    "Data Type Examples.8 Bit Device._Hints.USER (Rate, UserVal1, UserVal2, ... , UserValN) LLong": "true",
    "Data Type Examples.8 Bit Device._Hints.USER (Rate, UserVal1, UserVal2, ... , UserValN) Long": "true",
    "Data Type Examples.8 Bit Device._Hints.USER (Rate, UserVal1, UserVal2, ... , UserValN) QWord": "true",
    "Data Type Examples.8 Bit Device._Hints.USER (Rate, UserVal1, UserVal2, ... , UserValN) Short": "true",
    "Data Type Examples.8 Bit Device._Hints.USER (Rate, UserVal1, UserVal2, ... , UserValN) String": "true",
    "Data Type Examples.8 Bit Device._Hints.USER (Rate, UserVal1, UserVal2, ... , UserValN) Word": "true",
    "Data Type Examples.8 Bit Device.B Registers": "true",
    "Data Type Examples.8 Bit Device.B Registers.Boolean1": "true",
    "Data Type Examples.8 Bit Device.B Registers.Boolean2": "true",
    "Data Type Examples.8 Bit Device.B Registers.Boolean3": "true",
    "Data Type Examples.8 Bit Device.B Registers.Boolean4": "true",
    "Data Type Examples.8 Bit Device.B Registers.BooleanArray": "true",
    "Data Type Examples.8 Bit Device.K Registers": "true",
    "Data Type Examples.8 Bit Device.K Registers.Boolean1": "true",
    "Data Type Examples.8 Bit Device.K Registers.Boolean2": "true",
    "Data Type Examples.8 Bit Device.K Registers.Boolean3": "true",
    "Data Type Examples.8 Bit Device.K Registers.Boolean4": "true",
    "Data Type Examples.8 Bit Device.K Registers.Byte1": "true",
    "Data Type Examples.8 Bit Device.K Registers.Byte2": "true",
    "Data Type Examples.8 Bit Device.K Registers.Byte3": "true",
    "Data Type Examples.8 Bit Device.K Registers.Byte4": "true",
    "Data Type Examples.8 Bit Device.K Registers.ByteArray": "true",
    "Data Type Examples.8 Bit Device.K Registers.Char1": "true",
    "Data Type Examples.8 Bit Device.K Registers.Char2": "true",
    "Data Type Examples.8 Bit Device.K Registers.Char3": "true",
    "Data Type Examples.8 Bit Device.K Registers.Char4": "true",
    "Data Type Examples.8 Bit Device.K Registers.CharArray": "true",
    "Data Type Examples.8 Bit Device.K Registers.Double1": "true",
    "Data Type Examples.8 Bit Device.K Registers.Double2": "true",
    "Data Type Examples.8 Bit Device.K Registers.Double3": "true",
    "Data Type Examples.8 Bit Device.K Registers.Double4": "true",
    "Data Type Examples.8 Bit Device.K Registers.DoubleArray": "true",
    "Data Type Examples.8 Bit Device.K Registers.DWord1": "true",
    "Data Type Examples.8 Bit Device.K Registers.DWord2": "true",
    "Data Type Examples.8 Bit Device.K Registers.DWord3": "true",
    "Data Type Examples.8 Bit Device.K Registers.DWord4": "true",
    "Data Type Examples.8 Bit Device.K Registers.DWordArray": "true",
    "Data Type Examples.8 Bit Device.K Registers.Float1": "true",
    "Data Type Examples.8 Bit Device.K Registers.Float2": "true",
    "Data Type Examples.8 Bit Device.K Registers.Float3": "true",
    "Data Type Examples.8 Bit Device.K Registers.Float4": "true",
    "Data Type Examples.8 Bit Device.K Registers.FloatArray": "true",
    "Data Type Examples.8 Bit Device.K Registers.LLong1": "true",
    "Data Type Examples.8 Bit Device.K Registers.LLong2": "true",
    "Data Type Examples.8 Bit Device.K Registers.LLong3": "true",
    "Data Type Examples.8 Bit Device.K Registers.LLong4": "true",
    "Data Type Examples.8 Bit Device.K Registers.LLongArray": "true",
    "Data Type Examples.8 Bit Device.K Registers.Long1": "true",
    "Data Type Examples.8 Bit Device.K Registers.Long2": "true",
    "Data Type Examples.8 Bit Device.K Registers.Long3": "true",
    "Data Type Examples.8 Bit Device.K Registers.Long4": "true",
    "Data Type Examples.8 Bit Device.K Registers.LongArray": "true",
    "Data Type Examples.8 Bit Device.K Registers.QWord1": "true",
    "Data Type Examples.8 Bit Device.K Registers.QWord2": "true",
    "Data Type Examples.8 Bit Device.K Registers.QWord3": "true",
    "Data Type Examples.8 Bit Device.K Registers.QWord4": "true",
    "Data Type Examples.8 Bit Device.K Registers.QWordArray": "true",
    "Data Type Examples.8 Bit Device.K Registers.Short1": "true",
    "Data Type Examples.8 Bit Device.K Registers.Short2": "true",
    "Data Type Examples.8 Bit Device.K Registers.Short3": "true",
    "Data Type Examples.8 Bit Device.K Registers.Short4": "true",
    "Data Type Examples.8 Bit Device.K Registers.ShortArray": "true",
    "Data Type Examples.8 Bit Device.K Registers.Word1": "true",
    "Data Type Examples.8 Bit Device.K Registers.Word2": "true",
    "Data Type Examples.8 Bit Device.K Registers.Word3": "true",
    "Data Type Examples.8 Bit Device.K Registers.Word4": "true",
    "Data Type Examples.8 Bit Device.K Registers.WordArray": "true",
    "Data Type Examples.8 Bit Device.R Registers": "true",
    "Data Type Examples.8 Bit Device.R Registers.Boolean1": "true",
    "Data Type Examples.8 Bit Device.R Registers.Boolean2": "true",
    "Data Type Examples.8 Bit Device.R Registers.Boolean3": "true",
    "Data Type Examples.8 Bit Device.R Registers.Boolean4": "true",
    "Data Type Examples.8 Bit Device.R Registers.Byte1": "true",
    "Data Type Examples.8 Bit Device.R Registers.Byte2": "true",
    "Data Type Examples.8 Bit Device.R Registers.Byte3": "true",
    "Data Type Examples.8 Bit Device.R Registers.Byte4": "true",
    "Data Type Examples.8 Bit Device.R Registers.ByteArray": "true",
    "Data Type Examples.8 Bit Device.R Registers.Char1": "true",
    "Data Type Examples.8 Bit Device.R Registers.Char2": "true",
    "Data Type Examples.8 Bit Device.R Registers.Char3": "true",
    "Data Type Examples.8 Bit Device.R Registers.Char4": "true",
    "Data Type Examples.8 Bit Device.R Registers.CharArray": "true",
    "Data Type Examples.8 Bit Device.R Registers.Double1": "true",
    "Data Type Examples.8 Bit Device.R Registers.Double2": "true",
    "Data Type Examples.8 Bit Device.R Registers.Double3": "true",
    "Data Type Examples.8 Bit Device.R Registers.Double4": "true",
    "Data Type Examples.8 Bit Device.R Registers.DoubleArray": "true",
    "Data Type Examples.8 Bit Device.R Registers.DWord1": "true",
    "Data Type Examples.8 Bit Device.R Registers.DWord2": "true",
    "Data Type Examples.8 Bit Device.R Registers.DWord3": "true",
    "Data Type Examples.8 Bit Device.R Registers.DWord4": "true",
    "Data Type Examples.8 Bit Device.R Registers.DWordArray": "true",
    "Data Type Examples.8 Bit Device.R Registers.Float1": "true",
    "Data Type Examples.8 Bit Device.R Registers.Float2": "true",
    "Data Type Examples.8 Bit Device.R Registers.Float3": "true",
    "Data Type Examples.8 Bit Device.R Registers.Float4": "true",
    "Data Type Examples.8 Bit Device.R Registers.FloatArray": "true",
    "Data Type Examples.8 Bit Device.R Registers.LLong1": "true",
    "Data Type Examples.8 Bit Device.R Registers.LLong2": "true",
    "Data Type Examples.8 Bit Device.R Registers.LLong3": "true",
    "Data Type Examples.8 Bit Device.R Registers.LLong4": "true",
    "Data Type Examples.8 Bit Device.R Registers.LLongArray": "true",
    "Data Type Examples.8 Bit Device.R Registers.Long1": "true",
    "Data Type Examples.8 Bit Device.R Registers.Long2": "true",
    "Data Type Examples.8 Bit Device.R Registers.Long3": "true",
    "Data Type Examples.8 Bit Device.R Registers.Long4": "true",
    "Data Type Examples.8 Bit Device.R Registers.LongArray": "true",
    "Data Type Examples.8 Bit Device.R Registers.QWord1": "true",
    "Data Type Examples.8 Bit Device.R Registers.QWord2": "true",
    "Data Type Examples.8 Bit Device.R Registers.QWord3": "true",
    "Data Type Examples.8 Bit Device.R Registers.QWord4": "true",
    "Data Type Examples.8 Bit Device.R Registers.QWordArray": "true",
    "Data Type Examples.8 Bit Device.R Registers.Short1": "true",
    "Data Type Examples.8 Bit Device.R Registers.Short2": "true",
    "Data Type Examples.8 Bit Device.R Registers.Short3": "true",
    "Data Type Examples.8 Bit Device.R Registers.Short4": "true",
    "Data Type Examples.8 Bit Device.R Registers.ShortArray": "true",
    "Data Type Examples.8 Bit Device.R Registers.Word1": "true",
    "Data Type Examples.8 Bit Device.R Registers.Word2": "true",
    "Data Type Examples.8 Bit Device.R Registers.Word3": "true",
    "Data Type Examples.8 Bit Device.R Registers.Word4": "true",
    "Data Type Examples.8 Bit Device.R Registers.WordArray": "true",
    "Data Type Examples.8 Bit Device.S Registers": "true",
    "Data Type Examples.8 Bit Device.S Registers.String1": "true",
    "Data Type Examples.8 Bit Device.S Registers.String2": "true",
    "Data Type Examples.8 Bit Device.S Registers.String3": "true",
    "Data Type Examples.8 Bit Device.S Registers.String4": "true",
    "Data Type Examples.8 Bit Device.S Registers.StringArray[4]": "true",
    "MQTTlocalhost7883": "true",
    "MQTTlocalhost7883.a4GATE": "true",
    "MQTTlocalhost7883.a4GATE.B": "true",
    "MQTTlocalhost7883.a4GATE.B.SiteManager": "true",
    "MQTTlocalhost7883.a4GATE.B.tf_http_xfer_b": "true",
    "MQTTlocalhost7883.a4GATE.SiteManager": "true",
    "MQTTlocalhost7883.a4GATE.SiteManager.Color": "true",
    "MQTTlocalhost7883.a4GATE.SiteManager.Status": "true",
    "MQTTlocalhost7883.a4GATE.U2U": "true",
    "MQTTlocalhost7883.a4GATE.U2U.BIDIR": "true",
    "MQTTlocalhost7883.a4GATE.U2U.RT": "true",
    "MQTTlocalhost7883.Recipe": "true"

}

export { dummy_tags }



